Repository UMC-SAVVY/SAVVY_Server, pull requests merged in 2023-08, with the labels that each got.

#116 Fix : 다이어리 삭제 API 코드 오류 수정
  src/app/Diary/diaryService.js
Labels: bug

#118 Fix : 코드 에러 수정
  src/app/Diary/diaryProvider.js
Labels: bug

#120 Update :홈 조회 API 요청 시의 response 일부 변경
  src/app/Diary/diaryProvider.js
Labels: enhancement

#121 Feat : 댓글 수정, 답글 수정 API 추가
  config/baseResponseStatus.js
  src/app/Comment/commentController.js
  src/app/Comment/commentDao.js
  src/app/Comment/commentProvider.js
  src/app/Comment/commentRoute.js
  src/app/Comment/commentService.js
Labels: enhancement

#122 Feat : 댓글 삭제, 답글 삭제 API 추가
  src/app/Comment/commentController.js
  src/app/Comment/commentDao.js
  src/app/Comment/commentProvider.js
  src/app/Comment/commentRoute.js
  src/app/Comment/commentService.js
Labels: enhancement

#124 Feat: 마이페이지 API 추가
  src/app/Diary/diaryDao.js
  src/app/Diary/diaryProvider.js
  src/app/Planner/plannerDao.js
  src/app/User/userController.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: enhancement

#126 Feat: 체크리스트 API
  config/baseResponseStatus.js
  src/app/Planner/plannerController.js
  src/app/Planner/plannerRoute.js
  src/app/Planner/plannerService.js
Labels: enhancement

#128 Update: 세부내용 API 이미지 반환 추가
  src/app/Planner/plannerDao.js
Labels: enhancement

#130 Feat : 다이어리 신고, 댓글 및 답글 신고 API 추가 / Update :플래너 신고시 본인이 본인 플래너를 신고하지 못하도록 처리
  config/baseResponseStatus.js
  src/app/Comment/commentController.js
  src/app/Comment/commentDao.js
  src/app/Comment/commentProvider.js
  src/app/Comment/commentRoute.js
  src/app/Comment/commentService.js
  src/app/Diary/diaryController.js
  src/app/Diary/diaryDao.js
  src/app/Diary/diaryProvider.js
  src/app/Diary/diaryRoute.js
  src/app/Diary/diaryService.js
  src/app/Planner/plannerService.js
Labels: enhancement

#131 Update: 마이페이지 데이터 집계 추가
  src/app/User/userProvider.js
Labels: enhancement

#133 Add : 다이어리 검색 API 추가
  src/app/Diary/diaryController.js
  src/app/Diary/diaryDao.js
  src/app/Diary/diaryProvider.js
  src/app/Diary/diaryRoute.js
Labels: enhancement

#136 Fix: 여행계획서 목록 버그 수정
  src/app/Planner/plannerDao.js
Labels: bug

#139 Update: 마이페이지 API 수정
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: bug, enhancement

#141 Feat: 닉네임 중복확인 API
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: enhancement

#147 Feat: 차단 목록 API
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: enhancement

#149 Feat: 알림 목록 API
  config/baseResponseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
Labels: enhancement

#152 Update : 다이어리 댓글 수 상태 업데이트
  src/app/Comment/commentDao.js
  src/app/Comment/commentService.js
Labels: enhancement

#154 Fix: diaryService.js 수정
  src/app/Diary/diaryService.js
Labels: bug

#155 Fix : 다이어리 작성 시 오류 수정
  src/app/Diary/diaryController.js
  src/app/Diary/diaryDao.js
  src/app/Diary/diaryService.js
Labels: enhancement

#157 Update : 다이어리 검색 Response 수정
  src/app/Diary/diaryDao.js
Labels: enhancement

#160 Fix: user, searching, planner -> connection.release 버그 수정
  src/app/Planner/plannerProvider.js
  src/app/Planner/plannerService.js
  src/app/Searching/searchingProvider.js
  src/app/Searching/searchingService.js
  src/app/User/userProvider.js
Labels: bug

#161 Update : Connection 관련 코드 수정
  src/app/Comment/commentProvider.js
  src/app/Comment/commentService.js
  src/app/Diary/diaryProvider.js
  src/app/Diary/diaryService.js
Labels: enhancement

#165 Feat : 프로필 편집 API 추가
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: enhancement

#167 Fix: 업로드된 여행계획서 삭제 처리 수정
  src/app/Diary/diaryService.js
Labels: bug, enhancement

#169 Feat: 업로드된 여행계획서 내리는 기능
  src/app/Planner/plannerController.js
  src/app/Planner/plannerDao.js
  src/app/Planner/plannerRoute.js
  src/app/Planner/plannerService.js
Labels: enhancement

#171 Feat : 다이어리 좋아요 목록 보기 API 추가
  src/app/Diary/diaryProvider.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: enhancement

#173 Feat: 회원탈퇴 API
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: enhancement

#175 Feat : 신고시 다이어리, 댓글답글 상태 처리 추가
  config/baseResponseStatus.js
  src/app/Comment/commentDao.js
  src/app/Comment/commentProvider.js
  src/app/Comment/commentService.js
  src/app/Diary/diaryDao.js
  src/app/Diary/diaryService.js
Labels: enhancement

#176 Fix: 로그인 API is_deleted 버그 수정
  src/app/User/userProvider.js
Labels: bug

#178 Feat: 차단 목록 해제 API
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: enhancement
